### ISSUE TITLE
Extensions failing when using core 1.21 or later

### ISSUE THREAD

**Issue by carljonescf** [structurizr/java-extensions#71]
### Description

I'm using the Spring extension and the annotations support with Structurizr for Java. All is good with core/client versions up to 1.20.x, but 1.21 introduces a bug with this stack trace.

java.lang.NoSuchMethodError: 'com.structurizr.model.Component com.structurizr.model.Container.addComponent(java.lang.String, java.lang.String, java.lang.String, java.lang.String)'
	at com.structurizr.analysis.AbstractComponentFinderStrategy.addComponent(AbstractComponentFinderStrategy.java:211)
	at com.structurizr.analysis.AbstractComponentFinderStrategy.findClassesWithAnnotation(AbstractComponentFinderStrategy.java:181)
	at com.structurizr.analysis.SpringRestControllerComponentFinderStrategy.doFindComponents(SpringRestControllerComponentFinderStrategy.java:18)
	at com.structurizr.analysis.AbstractComponentFinderStrategy.findComponents(AbstractComponentFinderStrategy.java:57)
	at com.structurizr.analysis.SpringComponentFinderStrategy.doFindComponents(SpringComponentFinderStrategy.java:62)
	at com.structurizr.analysis.AbstractComponentFinderStrategy.findComponents(AbstractComponentFinderStrategy.java:57)
	at com.structurizr.analysis.ComponentFinder.findComponents(ComponentFinder.java:77)

I notice that a breaking change is noted on 1.21.

For my purposes, 1.20.x is fine, but just thought I should alert you to this.

### Steps to reproduce

Write Java code that uses the Spring Component Finder.

Expect the components to be found and added to the model.

Actual : stack trace above.

### Severity

Minor

### Priority

Low

### Resolution

I have no budget and there's no rush, please fix this for free

**Comment by simonbrowndotje** [comment]
See https://github.com/structurizr/java-extensions/discussions/69 ... the analysis library requires a big update I'm afraid.

**Comment by carljonescf** [comment]
Hi

That's a pity and slightly disappointing to read that it has little use.

I find it enlightening to give this to my students and show them just how much that can generate in 16 people-weeks. It opens up the discussion on imagining what bigger applications might look like after many months/years and (hopefully) makes the students realise the benefits of some planned design work.

Thanks
Carl
